from enum import Enum


class StockSymbolsEnum(Enum):
    TWILIO = "TWLO"
    APPLE = "AAPL"
    AMAZON = "AMZN"
    GOOGLE = "GOOGL"
    MICROSOFT = "MSFT"
    BARCLAYS = "BARC"
    IBM = "IBM"
    METLIFE = "MET"
    PHILIPS = "PHIA"
    PHILIP_MORRIS = "PM"
    UPS = "UPS"
    AMD = "AMD"
    HONEYWELL = "HON"
    MASTERCARD = "MA"
    MSI = "MSI"
    NVIDIA = "NVDA"
    PURE_STORAGE = "PSTG"
    SENTINEL_ONE = "S"
    SPLUNK = "SPLK"
    VISA = "V"
    CATERPILLAR = "CAT"
    COLGATE = "CL"
    FEDEX = "FDX"
    GENERAL_ELECTRIC = "GE"
    JOHNSON = "JNJ"
    MERK = "MRK"
    PEPSI = "PEP"
    PG = "PG"
    STARBUCKS = "SBUX"
    SCHWAB = "SCHW"
    SHELL = "SHEL"
    BP = "BP"
    PETROLEO_BRASILEIRO = "PBR"
    VOLKSWAGEN = "VOW"
    CISCO = "CSCO"
    ASTRA_SPACE = "ASTR"
    VIRGIN_GALACTIC = "SPCE"
